import { useState } from 'react';
import Icon from '../components/Icons';
import ContentGrid from '../components/ContentGrid';
import { Link } from '../components/Layout';
import { Breadcrumbs, ChapterSelect, EmptyState, FilterSearch, PageHero, SubjectCard, SubjectSelect } from '../components/UI';
import { chaptersBySubject, generalCategories, resourceCategories, subjects } from '../data/content';
import { useContent } from '../hooks/useContent';

export function Subjects(){return <><PageHero eyebrow="المواد الدراسية" title="كل المواد في مساحة واحدة" description="اختر مادتك للوصول إلى تقسيماتها وملخصاتها وأسئلتها ومصادرها عند إضافتها."><Breadcrumbs items={[{label:'المواد الدراسية'}]}/></PageHero><section className="section"><div className="container"><div className="subjects-grid">{subjects.map(s=><SubjectCard key={s.id} subject={s}/>)}</div></div></section></>}

export function SubjectDetail({id}){const subject=subjects.find(s=>s.id===id); if(!subject)return <NotFound/>; const chapters=chaptersBySubject[id]||[]; const division=subject.division; return <><PageHero eyebrow="صفحة المادة" title={subject.name} description={`مساحة المادة المستقلة، جاهزة لإضافة ${division.plural} ومحتواها دون التأثير في بقية المواد.`}><Breadcrumbs items={[{label:'المواد الدراسية',to:'/subjects'},{label:subject.name}]}/></PageHero><section className="section"><div className="container"><div className="subject-banner" style={{'--subject':subject.color}}><span className="subject-icon large">{subject.icon}</span><div><h2>{subject.name}</h2><p>أضف {division.plural} هذه المادة بشكل مستقل داخل ملف البيانات، وستظهر هنا تلقائيًا.</p></div><span className="resource-pill">0 مصدر</span></div><div className="content-tabs"><Link to={`/summaries?subject=${id}`}>الملخصات</Link><Link to={`/ministry?subject=${id}`}>الوزاريات</Link><Link to={`/questions?subject=${id}`}>الأسئلة</Link><Link to={`/exams?subject=${id}`}>الاختبارات</Link><Link to={`/resources?subject=${id}`}>المصادر</Link></div><div className="section-heading mini"><div><h2>{division.plural} المادة</h2><p>تدعم هذه المساحة إضافة {division.plural} وحذفها وترتيبها لكل مادة على حدة.</p></div></div>{chapters.length?<div className="cards-grid">{chapters.map(c=><div className="content-card" key={c.id}>{c.name}</div>)}</div>:<EmptyState title={`لم تُضف ${division.plural} لهذه المادة بعد`} text={`ستظهر ${division.plural} هنا تلقائيًا بعد إضافتها إلى بنية بيانات المادة.`}/>}</div></section></>}

const pageConfigs={
 summaries:{eyebrow:'مكتبة الملخصات',title:'الملخصات الدراسية',description:'واجهة مرتبة للوصول إلى الملخصات حسب المادة وتقسيمها والتصنيف.',data:'summaries',icon:'file'},
 ministry:{eyebrow:'الأسئلة الوزارية',title:'الوزاريات',description:'مساحة مخصصة لتنظيم الأسئلة الوزارية الأصلية بحسب المادة وتقسيمها والسنة والدور.',data:'ministryExams',icon:'book'},
 questions:{eyebrow:'تدرّب بتركيز',title:'بنك الأسئلة',description:'اعثر على الأسئلة الأكاديمية باستخدام فلاتر دقيقة ومرنة.',data:'questions',icon:'chat'},
};
export function ListingPage({type}){const cfg=pageConfigs[type];const dbType=type==='summaries'?'summary':type;const {items,loading,error}=useContent(dbType);const params=new URLSearchParams(location.search);const [subject,setSubject]=useState(params.get('subject')||'');const [chapter,setChapter]=useState('');const [search,setSearch]=useState('');const selectedSubject=subjects.find(item=>item.id===subject);const divisionVisible=!selectedSubject?.division.visibleIn||selectedSubject.division.visibleIn.includes(type);const filtered=items.filter(item=>(!subject||item.subject_id===subject)&&(!chapter||item.division_id===chapter)&&(!search||`${item.title} ${item.description||''} ${item.body||''}`.includes(search)));return <><PageHero eyebrow={cfg.eyebrow} title={cfg.title} description={cfg.description}><Breadcrumbs items={[{label:cfg.title}]}/></PageHero><section className="section"><div className="container"><div className="filter-panel"><div className="filter-head"><div><h2>ابحث وصفِّ النتائج</h2><p>اختر ما يناسبك للوصول إلى المحتوى المطلوب.</p></div><button className="clear-button" onClick={()=>{setSubject('');setChapter('');setSearch('')}}>مسح الفلاتر</button></div><div className="filters"><FilterSearch value={search} onChange={e=>setSearch(e.target.value)} placeholder={`ابحث في ${cfg.title}…`}/><SubjectSelect value={subject} onChange={e=>{setSubject(e.target.value);setChapter('')}}/>{divisionVisible&&<ChapterSelect subjectId={subject} value={chapter} onChange={e=>setChapter(e.target.value)}/>} {type==='summaries'&&<select aria-label="الترتيب"><option>الأحدث أولًا</option><option>الأقدم أولًا</option><option>أبجديًا</option></select>}{type==='ministry'&&<><select aria-label="السنة"><option>جميع السنوات</option></select><select aria-label="الدور"><option>جميع الأدوار</option><option>الدور الأول</option><option>الدور الثاني</option></select></>}{type==='questions'&&<><select aria-label="الصعوبة"><option>كل مستويات الصعوبة</option><option>سهل</option><option>متوسط</option><option>صعب</option></select><select aria-label="نوع السؤال"><option>جميع أنواع الأسئلة</option><option>اختيار من متعدد</option><option>إجابة نصية</option></select></>}</div></div><div className="results-head"><h2>النتائج</h2><span>{filtered.length} عنصر</span></div><ContentGrid items={filtered} loading={loading} error={error} emptyText={`ستظهر ${cfg.title} الحقيقية هنا بعد نشرها من لوحة الإدارة.`}/></div></section></>}

export function GeneralQA(){const [active,setActive]=useState('الكل');const [q,setQ]=useState('');const {items,loading,error}=useContent('experience');const filtered=items.filter(item=>(active==='الكل'||item.category===active)&&(!q||`${item.title} ${item.description||''} ${item.body||''}`.includes(q)));return <><PageHero eyebrow="خبرات طلابية" title="الأسئلة والأجوبة العامة حول السادس" description="مساحة مستقلة للأسئلة والتجارب الواقعية المتعلقة برحلة السادس الإعدادي، وليست بنكًا للأسئلة الأكاديمية."><Breadcrumbs items={[{label:'الأسئلة والأجوبة العامة'}]}/></PageHero><section className="section"><div className="container"><div className="qa-toolbar"><FilterSearch value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث في الأسئلة والتجارب…"/><div className="category-chips"><button className={active==='الكل'?'active':''} onClick={()=>setActive('الكل')}>الكل</button>{generalCategories.map(c=><button className={active===c?'active':''} onClick={()=>setActive(c)} key={c}>{c}</button>)}</div></div><div className="info-strip"><Icon name="check"/><p>لا يظهر هنا إلا المحتوى الحقيقي الذي نشره مدير المنصة.</p></div><ContentGrid items={filtered} loading={loading} error={error} emptyText="لا توجد أسئلة أو تجارب منشورة حاليًا."/></div></section></>}

export function Resources(){const [active,setActive]=useState('الكل');const {items,loading,error}=useContent('resource');const filtered=active==='الكل'?items:items.filter(item=>item.category===active);return <><PageHero eyebrow="مكتبة موثوقة" title="المصادر" description="مكان منظم للكتب والملفات والمصادر الرسمية والروابط المفيدة بعد إضافتها والتحقق منها."><Breadcrumbs items={[{label:'المصادر'}]}/></PageHero><section className="section"><div className="container"><div className="category-cards"><button className={active==='الكل'?'active':''} onClick={()=>setActive('الكل')}><Icon name="grid"/><span>جميع المصادر</span><b>{items.length}</b></button>{resourceCategories.map((c,i)=><button className={active===c?'active':''} onClick={()=>setActive(c)} key={c}><Icon name={i<2?'file':i===2?'check':'link'}/><span>{c}</span><b>{items.filter(item=>item.category===c).length}</b></button>)}</div><div className="results-head"><h2>{active==='الكل'?'جميع المصادر':active}</h2><span>{filtered.length} مصدر</span></div><ContentGrid items={filtered} loading={loading} error={error} emptyText="لا توجد مصادر منشورة حاليًا."/></div></section></>}

export function Search(){const [q,setQ]=useState('');const [searched,setSearched]=useState(false);const [type,setType]=useState('all');const {items,loading,error}=useContent();const typeMap={summaries:'summary',ministry:'ministry',questions:'question',exams:'exam',resources:'resource',experiences:'experience'};const results=searched&&q?items.filter(item=>(type==='all'||item.type===typeMap[type])&&`${item.title} ${item.description||''} ${item.body||''} ${item.source_name||''}`.includes(q)):[];const submit=e=>{e.preventDefault();setSearched(true)};return <><PageHero eyebrow="البحث الشامل" title="اعثر على ما تحتاجه بسرعة" description="ابحث عبر جميع أنواع المحتوى المنشور من واجهة واحدة."><Breadcrumbs items={[{label:'البحث'}]}/></PageHero><section className="section"><div className="container narrow"><form className="big-search" onSubmit={submit}><Icon name="search"/><input value={q} onChange={e=>{setQ(e.target.value);setSearched(false)}} placeholder="اكتب كلمة أو عنوانًا للبحث…" autoFocus/><button className="button primary" type="submit">بحث</button></form><div className="search-types">{[['all','الكل'],['summaries','الملخصات'],['ministry','الوزاريات'],['questions','الأسئلة'],['exams','الاختبارات'],['resources','المصادر'],['experiences','التجارب']].map(([id,n])=><button key={id} className={type===id?'active':''} onClick={()=>setType(id)}>{n}</button>)}</div>{searched&&q?<ContentGrid items={results} loading={loading} error={error} emptyText={`لم نجد نتائج مطابقة لعبارة «${q}».`}/>:<EmptyState title="ابدأ بكتابة ما تبحث عنه" text="يمكنك البحث في الملخصات والوزاريات والأسئلة والاختبارات والمصادر والتجارب." icon="search"/>}</div></section></>}

export function About(){return <><PageHero eyebrow="عن المنصة" title="مساحة تعليمية أوضح للطالب العراقي" description="بُنيت منصة السادس الإعدادي لتجعل الوصول إلى الموارد التعليمية المنظمة أبسط وأكثر مباشرة."><Breadcrumbs items={[{label:'حول الموقع'}]}/></PageHero><section className="section"><div className="container about-grid"><div className="about-main"><span className="eyebrow">لماذا هذه المنصة؟</span><h2>لأن تنظيم المعلومة جزء من التعلّم</h2><p>يواجه طالب السادس الإعدادي كمًا كبيرًا من المواد والملفات والأسئلة المتفرقة. تهدف المنصة إلى تقديم بنية واحدة واضحة تساعده على الوصول إلى المحتوى الأصيل عند إضافته، بحسب المادة والفصل والنوع.</p><p>المنصة موجهة لطلبة السادس الإعدادي في العراق، ومصممة لتبقى مجانية وسهلة الاستخدام على الهاتف والحاسوب.</p><div className="values"><div><Icon name="layers"/><h3>تنظيم واضح</h3><p>مسارات مباشرة للمادة ونوع المحتوى.</p></div><div><Icon name="check"/><h3>محتوى مسؤول</h3><p>لا تُعرض مواد تعليمية مختلقة أو غير موثقة.</p></div><div><Icon name="grid"/><h3>قابلة للتوسع</h3><p>بنية جاهزة للنمو مع احتياجات الطلبة.</p></div></div></div><aside className="about-aside"><img className="visual-logo" src="/app-icon.svg" alt="أيقونة السادس الإعدادي"/><h3>السادس الإعدادي</h3><p>منصة تعليمية مستقلة، وليست تابعة أو ممثلة لوزارة التربية العراقية.</p><hr/><span>المرحلة الحالية</span><strong>واجهة أمامية جاهزة للمحتوى</strong></aside></div></section></>}

export function NotFound(){return <section className="section not-found"><div className="container"><strong>404</strong><h1>الصفحة غير موجودة</h1><p>قد يكون الرابط غير صحيح أو أن الصفحة نُقلت.</p><Link to="/" className="button primary">العودة إلى الرئيسية</Link></div></section>}
