import Icon from '../components/Icons';
import { Link } from '../components/Layout';
import { EmptyState, SubjectCard } from '../components/UI';
import { subjects } from '../data/content';
import { useContent } from '../hooks/useContent';

const quick = [
  ['/summaries','الملخصات','مواد مرتبة حسب المادة والفصل','file'], ['/ministry','الوزاريات','واجهة للأسئلة الوزارية الأصلية','book'], ['/questions','بنك الأسئلة','أسئلة أكاديمية قابلة للتصفية','chat'],
  ['/exams','الاختبارات','تجربة تدريب منظمة ومتكاملة','check'], ['/general-qa','الأسئلة العامة','خبرات وتجارب طلابية موثوقة','chat'], ['/resources','المصادر','كتب وملفات وروابط مفيدة','link'],
];
export default function Home(){const {items:resources}=useContent('resource');return <>
  <section className="home-hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow light">من الطالب العراقي، ولأجله</span><h1>كل ما تحتاجه في السادس،<br/><mark>مرتب في مكان واحد.</mark></h1><p>منصة تعليمية تجمع المواد والملخصات والوزاريات والاختبارات في تجربة واضحة تساعدك على الوصول إلى ما تحتاجه دون تشتّت.</p><div className="hero-actions"><Link to="/subjects" className="button primary">استكشف المواد <Icon name="arrow" size={19}/></Link><Link to="/about" className="button ghost">تعرّف على المنصة</Link></div><div className="hero-note"><Icon name="check" size={18}/> مجانية، مستقلة، ومصممة لطلاب العراق</div></div>
  <div className="hero-visual" aria-hidden="true"><div className="visual-orbit"><span>ع</span><span>En</span><span>⚛</span></div><div className="visual-card"><img className="visual-logo" src="/app-icon.svg" alt=""/><strong>مساحتك الدراسية</strong><small>تعلّم بوضوح • تقدّم بثقة</small><div className="visual-lines"><i/><i/><i/></div></div><div className="float-tag tag-1">مواد منظمة</div><div className="float-tag tag-2">وصول سريع</div></div></div></section>
  <section className="section"><div className="container"><div className="section-heading"><div><span className="eyebrow">المواد الدراسية</span><h2>ابدأ من مادتك</h2><p>بنية مستقلة لكل مادة، جاهزة لفصولها أو وحداتها أو مواضيعها الخاصة.</p></div><Link to="/subjects" className="text-link">عرض جميع المواد <Icon name="arrow" size={18}/></Link></div><div className="subjects-grid home-subjects">{subjects.map(s=><SubjectCard key={s.id} subject={s} resourceCount={resources.filter(item=>item.subject_id===s.id).length}/>)}</div></div></section>
  <section className="section soft"><div className="container"><div className="section-heading centered"><div><span className="eyebrow">وصول سريع</span><h2>اذهب مباشرة إلى وجهتك</h2><p>كل أدوات المنصة الأساسية في متناولك.</p></div></div><div className="quick-grid">{quick.map(([to,title,text,icon])=><Link to={to} className="quick-card" key={to}><span><Icon name={icon}/></span><div><h3>{title}</h3><p>{text}</p></div><Icon name="arrow" size={18}/></Link>)}</div></div></section>
  <section className="section"><div className="container split-section"><div className="experience-copy"><span className="eyebrow">من تجارب من سبقوك</span><h2>أسئلة وأجوبة عامة حول السادس</h2><p>قسم مستقل سيضم لاحقًا تجارب حقيقية وأسئلة شائعة من طلبة السادس السابقين، بصورة منظمة ومسؤولة.</p><Link to="/general-qa" className="button secondary">استكشف القسم <Icon name="arrow" size={18}/></Link></div><EmptyState title="بانتظار التجارب الحقيقية" text="لن نعرض هنا إلا محتوى حقيقيًا بعد إضافته ومراجعته." icon="chat"/></div></section>
  <section className="cta-band"><div className="container"><div><h2>ابدأ رحلتك من مكان واضح</h2><p>اختر المادة، ثم انتقل إلى نوع المحتوى الذي تحتاجه.</p></div><Link to="/subjects" className="button light-button">تصفّح المواد <Icon name="arrow" size={18}/></Link></div></section>
  </>}
