import Icon from './Icons';
import { Link } from './Layout';
import { chaptersBySubject, subjects } from '../data/content';

export function Breadcrumbs({ items=[] }) { return <nav className="breadcrumbs" aria-label="مسار الصفحة"><Link to="/">الرئيسية</Link>{items.map((x,i)=><span key={i}><b>/</b>{x.to ? <Link to={x.to}>{x.label}</Link> : <em>{x.label}</em>}</span>)}</nav> }
export function PageHero({ eyebrow, title, description, children }) { return <section className="page-hero"><div className="container"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p>{children}</div></section> }
export function EmptyState({ title='لا يوجد محتوى حاليًا', text='ستظهر المواد هنا بعد إضافتها من مصدر المحتوى.', icon='layers', compact=false }) { return <div className={`empty ${compact?'compact':''}`}><span className="empty-icon"><Icon name={icon} size={28}/></span><h3>{title}</h3><p>{text}</p></div> }
export function SubjectSelect({ value, onChange, allLabel='جميع المواد' }) { return <select value={value} onChange={onChange} aria-label="المادة"><option value="">{allLabel}</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select> }
export function ChapterSelect({ subjectId, value, onChange }) { const cs=chaptersBySubject[subjectId]||[]; const subject=subjects.find(s=>s.id===subjectId); const division=subject?.division||{singular:'فصل',plural:'فصول'}; return <select value={value} onChange={onChange} disabled={!subjectId||!cs.length} aria-label={division.singular}><option value="">{!subjectId?'اختر المادة أولًا':cs.length?`جميع الـ${division.plural}`:`لا توجد ${division.plural} مضافة`}</option>{cs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select> }
export function FilterSearch({ placeholder='ابحث في المحتوى…', value, onChange }) { return <label className="search-field"><Icon name="search" size={20}/><input value={value} onChange={onChange} placeholder={placeholder}/></label> }
export function SubjectCard({ subject }) { return <article className="subject-card" style={{'--subject':subject.color}}><div className="subject-icon">{subject.icon}</div><div className="subject-copy"><h3>{subject.name}</h3><p>{subject.description}</p></div><Link to={`/subjects/${subject.id}`} className="text-link">الدخول إلى المادة <Icon name="arrow" size={18}/></Link></article> }
